### ISSUE TITLE
JWS has invalid anti-replay nonce

### ISSUE THREAD

**Issue by rezaalavi** [unixcharles/acme-client#51]
Hi,

In the past couple of days I keep getting "JWS has invalid anti-replay nonce" and hence no certificate is issued.
Here is the error trace:
/usr/local/rvm/gems/ruby-2.1.5/gems/acme-client-0.2.4/lib/acme/client/faraday_middleware.rb:52:in `on_complete': JWS has invalid anti-replay nonce (Acme::Client::Error::BadNonce)
	from /usr/local/rvm/gems/ruby-2.1.5/gems/acme-client-0.2.4/lib/acme/client/faraday_middleware.rb:12:in `block in call'
	from /usr/local/rvm/gems/ruby-2.1.5/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
	from /usr/local/rvm/gems/ruby-2.1.5/gems/acme-client-0.2.4/lib/acme/client/faraday_middleware.rb:12:in `call'
	from /usr/local/rvm/gems/ruby-2.1.5/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /usr/local/rvm/gems/ruby-2.1.5/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /usr/local/rvm/gems/ruby-2.1.5/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from /usr/local/rvm/gems/ruby-2.1.5/gems/acme-client-0.2.4/lib/acme/client.rb:48:in `new_certificate'

**Comment by unixcharles** [comment]
I assume this is related to https://github.com/letsencrypt/boulder/issues/1217

They mentioned that we should retry when getting `BadNonce`, so that might be something to look into.

**Comment by will-in-wi** [comment]
It looks like on Jan 28, this may have been fixed upstream: https://github.com/letsencrypt/boulder/issues/1217#issuecomment-176474434

**Comment by unixcharles** [comment]
closing

**Comment by jeromegn** [comment]
I'm still getting those from time to time, seemingly randomly.

```
gems/acme-client-0.5.1/lib/acme/client/faraday_middleware.rb:43:in `raise_on_error!': JWS has invalid anti-replay nonce Vm4E72HeNwUxVyR9XZYcRgcR1cSViIatVQVRbt8vnb0 (Acme::Client::Error)
    from gems/acme-client-0.5.1/lib/acme/client/faraday_middleware.rb:33:in `on_complete'
    from gems/acme-client-0.5.1/lib/acme/client/faraday_middleware.rb:18:in `block in call'
    from gems/faraday-0.11.0/lib/faraday/response.rb:61:in `on_complete'
    from gems/acme-client-0.5.1/lib/acme/client/faraday_middleware.rb:18:in `call'
    from gems/faraday-0.11.0/lib/faraday/rack_builder.rb:139:in `build_response'
    from gems/faraday-0.11.0/lib/faraday/connection.rb:377:in `run_request'
    from gems/faraday-0.11.0/lib/faraday/connection.rb:177:in `post'
    from gems/acme-client-0.5.1/lib/acme/client.rb:58:in `authorize'
    from app/models/certificate.rb:66:in `reset_authorization!'
```

In my model's method, I'm calling `acme_client.authorize`. That's about it. The stacktrace shows this is where it starts going wrong :)

Unfortunately, I'm not getting a `BadNonce` error class here, so it's hard to know when I should retry (if I even should.)

**Comment by unixcharles** [comment]
> Unfortunately, I'm not getting a BadNonce error class here, so it's hard to know when I should retry (if I even should.)

What version of the client are you running?

I would expect this PR to fix that problem:

https://github.com/unixcharles/acme-client/pull/116

**Comment by jeromegn** [comment]
Good point. I thought I saw that PR actually, but I didn't think to check if I had the change.

I was running 0.5.1. Now upgraded to 0.5.5.

@unixcharles I don't expect that'll fix the actual error from happening though, right? I can't figure what triggers this. Looks like the boulder fix wasn't really a fix (they weren't sure what the real issue was.) We'll see if I still get some. I can always retry to create the authorization, that's for sure.

**Comment by unixcharles** [comment]
I been ignoring those for the past year. I have some retry mechanism and the certificate generally get provisioned on the following attempt.

I'm not against the idea of retrying from within the client. I think this specific request actually come with a new nonce token, so we could retry once right away easily.
